### ISSUE TITLE
1.16.5 FramedBlocks 2.7 Server-side crash

### ISSUE THREAD

**Issue by wendall911** [XFactHD/FramedBlocks#18]
Crashing when connecting where an Andesite button is present. Not sure the exact condition, and haven't reproduced:

net.minecraft.crash.ReportedException: Ticking player
    at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
    at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
    at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
    at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraftforge/common/extensions/IForgeBlock.getSlipperiness xfacthd/framedblocks/common/block/IFramedBloc
    at xfacthd.framedblocks.common.block.FramedButtonBlock.getSlipperiness(FramedButtonBlock.java) ~[framedblocks:2.7]
    at net.minecraftforge.common.extensions.IForgeBlockState.getSlipperiness(IForgeBlockState.java:71) ~[forge:?]
    at net.minecraft.entity.LivingEntity.func_213352_e(LivingEntity.java:2012) ~[?:?]
    at net.minecraft.entity.player.PlayerEntity.func_213352_e(PlayerEntity.java:1368) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2449) ~[?:?]
    at net.minecraft.entity.player.PlayerEntity.func_70636_d(PlayerEntity.java:489) ~[?:?]
    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
    at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
    at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]

**Comment by XFactHD** [comment]
I have found the issue, will publish a hotfix shortly

**Comment by wendall911** [comment]
Fantastic! Thank you.
