### ISSUE TITLE
crash;

### ISSUE THREAD

**Issue by RedMandiPandi** [XFactHD/FramedBlocks#291]
### Minecraft version

1.2

### Forge version

1.20.1-forge-47.0.3

### FramedBlocks version

FramedBlocks-9.0.3.jar

### Describe the bug

I installed your mod today and lunch my game and the crash happened 

### How to reproduce the bug

launch the game

### Expected behavior

the game to launch normally 

### Additional details

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-07-25 01:19:04
Description: Unexpected error

java.lang.IllegalStateException: Config property is not linked yet
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-forge-1.20.1-0.6.5.jar%23176!/:1.20.1-0.6.5] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.client.overlay.CursorOverlay.isVisible(CursorOverlay.java:25) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:classloading}
	at com.mrcrayfish.controllable.client.OverlayHandler.draw(OverlayHandler.java:40) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.handler$zbk000$controllableLastRender(GameRenderer.java:2133) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:998) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.3.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20.1-47.0.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-forge-1.20.1-0.6.5.jar%23176!/:1.20.1-0.6.5] {re:mixin,re:classloading}
	at com.mrcrayfish.controllable.client.overlay.CursorOverlay.isVisible(CursorOverlay.java:25) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:classloading}
	at com.mrcrayfish.controllable.client.OverlayHandler.draw(OverlayHandler.java:40) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.handler$zbk000$controllableLastRender(GameRenderer.java:2133) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.3.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20.1-47.0.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 257110512 bytes (245 MiB) / 738197504 bytes (704 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 27537.70
	Virtual memory used (MB): 14574.21
	Swap memory total (MB): 11264.00
	Swap memory used (MB): 420.42
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.0.3
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.0.3.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.0.3.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.0.3.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.0.3.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.0.3.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.0.3-universal.jar                 |Forge                         |forge                         |47.0.3              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

### Crash log

---- Minecraft Crash Report ---- // Uh... Did I do that?  Time: 2023-07-25 01:19:04 Description: Unexpected error  java.lang.IllegalStateException: Config property is not linked yet 	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-forge-1.20.1-0.6.5.jar%23176!/:1.20.1-0.6.5] {re:mixin,re:classloading} 	at com.mrcrayfish.controllable.client.overlay.CursorOverlay.isVisible(CursorOverlay.java:25) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:classloading} 	at com.mrcrayfish.controllable.client.OverlayHandler.draw(OverlayHandler.java:40) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:mixin,re:classloading} 	at net.minecraft.client.renderer.GameRenderer.handler$zbk000$controllableLastRender(GameRenderer.java:2133) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:998) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.3.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20.1-47.0.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-forge-1.20.1-0.6.5.jar%23176!/:1.20.1-0.6.5] {re:mixin,re:classloading} 	at com.mrcrayfish.controllable.client.overlay.CursorOverlay.isVisible(CursorOverlay.java:25) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:classloading} 	at com.mrcrayfish.controllable.client.OverlayHandler.draw(OverlayHandler.java:40) ~[controllable-forge-1.20.1-0.20.1.jar%23171!/:1.20.1-0.20.1] {re:mixin,re:classloading} 	at net.minecraft.client.renderer.GameRenderer.handler$zbk000$controllableLastRender(GameRenderer.java:2133) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:controllable.common.mixins.json:client.GameRendererMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeGameRendererMixin,pl:mixin:APP:create.mixins.json:client.GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A,pl:runtimedistcleaner:A} -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: No 	Packs: vanilla Stacktrace: 	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading} 	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2326) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:740) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:controllable.common.mixins.json:client.MinecraftMixin,pl:mixin:APP:controllable.mixins.json:client.ForgeMinecraftMixin,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.0.3.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {} 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {} 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {} 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {} 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:28) ~[fmlloader-1.20.1-47.0.3.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {} 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}   -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 257110512 bytes (245 MiB) / 738197504 bytes (704 MiB) up to 2147483648 bytes (2048 MiB) 	CPUs: 12 	Processor Vendor: GenuineIntel 	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz 	Identifier: Intel64 Family 6 Model 167 Stepping 1 	Microarchitecture: Rocket Lake 	Frequency (GHz): 2.59 	Number of physical packages: 1 	Number of physical CPUs: 6 	Number of logical CPUs: 12 	Graphics card #0 name: NVIDIA GeForce RTX 3060 	Graphics card #0 vendor: NVIDIA (0x10de) 	Graphics card #0 VRAM (MB): 4095.00 	Graphics card #0 deviceId: 0x2504 	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Virtual memory max (MB): 27537.70 	Virtual memory used (MB): 14574.21 	Swap memory total (MB): 11264.00 	Swap memory used (MB): 420.42 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Launched Version: 1.20.1-forge-47.0.3 	Backend library: LWJGL version 3.3.1 build 7 	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 511.79, NVIDIA Corporation 	Window size: 854x480 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages:  	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs:  	Current Language: en_us 	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz 	ModLauncher: 10.0.9+10.0.9+main.dcd20f30 	ModLauncher launch target: forgeclient 	ModLauncher naming: srg 	ModLauncher services:  		mixin-0.8.5.jar mixin PLUGINSERVICE  		eventbus-6.0.3.jar eventbus PLUGINSERVICE  		fmlloader-1.20.1-47.0.3.jar slf4jfixer PLUGINSERVICE  		fmlloader-1.20.1-47.0.3.jar object_holder_definalize PLUGINSERVICE  		fmlloader-1.20.1-47.0.3.jar runtime_enum_extender PLUGINSERVICE  		fmlloader-1.20.1-47.0.3.jar capability_token_subclass PLUGINSERVICE  		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE  		fmlloader-1.20.1-47.0.3.jar runtimedistcleaner PLUGINSERVICE  		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE  		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE  	FML Language Providers:  		minecraft@1.0 		lowcodefml@null 		javafml@null 	Mod List:  		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f 		forge-1.20.1-47.0.3-universal.jar                 |Forge                         |forge                         |47.0.3              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by XFactHD** [comment]
This crash report shows no evidence of FramedBlocks being at fault with the actual issue being hidden by another mod crashing while Forge is trying to reach the error screen. Please provide the latest.log file from the logs folder and please use a paste site like https://gist.github.com instead of throwing the log contents into your message.

**Comment by RedMandiPandi** [comment]
I'm extremely new to moded Minecraft and coping files so I'm not sure how to use https://gist.github.com properly. I really enjoyed this mod right before the new Minecraft release and was hoping to use it again. I can't figure out the conflict so I was hoping you could help thank you for any help or advice you are able to offer.

**Comment by XFactHD** [comment]
Reopening the issue as I assume you closed it by accident.

As for the log, if you go to the folder where you found the crash report you posted and then go up one folder, you'll find a bunch of folders, including the logs folder. Go into the logs folder and find the file that is called `latest.log` or `latest` and is of type `Text Document`. Then open https://gist.github.com/, pull the file over the text box and drop it there. Then click `Create secret gist`, copy the address from your browser's address bar and paste it into your message. When you provide the log, then I'll be happy to help you find what causes the problem.

**Comment by RedMandiPandi** [comment]
https://gist.github.com/RedMandiPandi/be07a6b3290f00be838d32172a8603c6

**Comment by XFactHD** [comment]
`Mod framedblocks requires forge 47.0.34 or above. Currently, forge is 47.0.3`
In other words: FramedBlocks requires a newer Forge version than the one you have installed. I would highly suggest using Forge 47.1.3 as that is a version a lot of mods require. To update, just run the installer while the launcher is closed and the launcher profile should be automatically updated to use the new version.

**Comment by RedMandiPandi** [comment]
thank you for all your help i will do that
