### ISSUE TITLE
[Bug]: Exiting Framing Saw crashes the game when JEI is not installed

### ISSUE THREAD

**Issue by mikerooni** [XFactHD/FramedBlocks#321]
### Minecraft version

1.2

### Forge version

47.1.3

### FramedBlocks version

9.1.2

### Describe the bug

Unfortunately, 9.1.2 didn't fix the issue completely (see #316).

I'm running REI instead of JEI in my modpack and the game still crashes when I exit the Framing Saw.

### How to reproduce the bug

- Install REI instead of JEI
- Open the Framing Saw GUI
- Exit the GUI

### Expected behavior

The game shouldn't crash when JEI is not installed.

### Additional details

Here's the relevant part of the stacktrace:

```
java.lang.NullPointerException: Runtime not set
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[guava-31.1-jre.jar%23109!/:?] {re:mixin}
	at xfacthd.framedblocks.common.compat.jei.JeiCompat$GuardedAccess.isShowRecipePressed(JeiCompat.java:66) ~[FramedBlocks-9.1.2.jar%23416!/:9.1.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at xfacthd.framedblocks.common.compat.jei.JeiCompat.isShowRecipePressed(JeiCompat.java:43) ~[FramedBlocks-9.1.2.jar%23416!/:9.1.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at xfacthd.framedblocks.client.util.RecipeViewer.isShowRecipePressed(RecipeViewer.java:25) ~[FramedBlocks-9.1.2.jar%23416!/:9.1.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at xfacthd.framedblocks.client.screen.FramingSawScreen.m_7933_(FramingSawScreen.java:483) ~[FramedBlocks-9.1.2.jar%23416!/:9.1.2] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.client.KeyboardHandler.lambda$keyPress$5(KeyboardHandler.java:383) ~[client-1.20.1-20230612.114412-srg.jar%23528!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:KeyboardHandlerMixin,pl:mixin:APP:supplementaries-common.mixins.json:KeyboardHandlerMixin,pl:mixin:APP:ad_astra-common.mixins.json:client.KeyboardHandlerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

**Comment by XFactHD** [comment]
REI's JEI compatibility layer strikes again. I'll have to see if there is any good way to detect this.

**Comment by XFactHD** [comment]
New version with the fix is approved on CurseForge

**Comment by mikerooni** [comment]
Awesome, thank you!
