### ISSUE TITLE
[Bug]: Registry Object not present: framedblocks:framed_threeway_corner

### ISSUE THREAD

**Issue by johnellinwood** [XFactHD/FramedBlocks#545]
### Minecraft version

1.18 - UNSUPPORTED

### (Neo)Forge version

40.2.14

### FramedBlocks version

5.11.5

### Describe the bug

StoneBlock 3, version 1.11.1, CurseForge 40.2.14
Windows 11 Pro 24H2
Intel(R) Core(TM) i9-14900KF   3.20 GHz
96.0 GB (95.8 GB usable)
Nvidia GeForce RTX 4070 Ti, Driver Version 566.36

Won't start on a fresh install of everything, curseforge, stoneblock, minecraft.  

```
Error loading mods
3 errors have occurred during loading
FramedBlocks (framedblocks) encountered an error during the common_setup event phase
java.lang.IncompatibleClassChangeError: Class [Z does not implement the requested interface net.minecraft.world.phys.shapes.IndexMerger$IndexConsumer
FramedBlocks (framedblocks) encountered an error during the error event phase
java.lang.NullPointerException Registry Object not present: framedblocks:framing_saw
FramedBlocks (framedblocks) encountered an error during the error event phase
java.lang.NullPointerException Registry Object not present: framedblocks:framed_threeway_corner
```

```
-- MOD framedblocks --
Details:
	Mod File: /C:/Users/Me/curseforge/minecraft/Instances/FTB StoneBlock 3/mods/FramedBlocks-5.11.5.jar
	Failure message: FramedBlocks (framedblocks) encountered an error during the error event phase
		java.lang.NullPointerException: Registry Object not present: framedblocks:framed_threeway_corner
	Mod Version: 5.11.5
	Mod Issue URL: https://www.github.com/xfacthd/framedblocks
	Exception message: java.lang.NullPointerException: Registry Object not present: framedblocks:framed_threeway_corner
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?] {re:mixin}
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:320) ~[forge-1.18.2-40.2.14-universal.jar%23281!/:?] {re:mixin,xf:fml:forge:registry_object_binary_compat,re:classloading,pl:rei_plugin_compatibilities:B,xf:fml:forge:registry_object_binary_compat}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
```

```
[11:24:26] [main/INFO]: ModLauncher running: args [--username, FusedManager652, --version, forge-40.2.14, --gameDir, C:\Users\Me\curseforge\minecraft\Instances\FTB StoneBlock 3, --assetsDir, C:\Users\Me\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, ffd8891e913247a89494c2cf90e704db, --accessToken, ????????, --clientId, MzBkMjEwNmItZWE1Mi00NzY2LTg1NWItZGYzYjRlNWI3YjFh, --xuid, 2535416730861952, --userType, msa, --versionType, release, --width, 1024, --height, 768, --launchTarget, forgeclient, --fml.forgeVersion, 40.2.14, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
[11:24:26] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
[11:24:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 
```

### How to reproduce the bug

fresh install of everything, curseforge, stoneblock3, minecraft. Just try to run the game.

### Expected behavior

Expect minecraft to start in stoneblock 3

### Crash log

https://gist.github.com/johnellinwood/f730c9ee87b05a13a791c73009b92acd

**Comment by XFactHD** [comment]
Two attempts at starting Stoneblock 3 worked fine for me. However, the specific error you are getting is very familiar to me and is almost guaranteed to be caused by memory stability issues. The Intel Core i9-14900KF you are using, just like the 13900K I am using, is plagued by a firmware bug that slowly destroys the CPU physically, which can also cause these memory issues. For mitigations and solutions to this I would recommend looking into the articles on this topic by various news outlets as well as Intel themselves.

**Comment by johnellinwood** [comment]
Ah, ok, that actually could be the problem. Thanks.
